# Use root/example as user/password credentials
# https://markheath.net/post/exploring-elasticsearch-with-docker
# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
version: '3.1'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: es01
    restart: always
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

volumes:
 esdata01:

networks:
 esnet: